<?php

function robertochoa_custom_post_type() {

    $labels = array(
        'name'                  => _x( 'Clientes', 'Post Type General Name', 'robertochoa' ),
        'singular_name'         => _x( 'Cliente', 'Post Type Singular Name', 'robertochoa' ),
        'menu_name'             => __( 'Clientes', 'robertochoa' ),
        'name_admin_bar'        => __( 'Clientes', 'robertochoa' ),
        'archives'              => __( 'Archivo de Clientes', 'robertochoa' ),
        'attributes'            => __( 'Atributos de Cliente', 'robertochoa' ),
        'parent_item_colon'     => __( 'Cliente Padre:', 'robertochoa' ),
        'all_items'             => __( 'Todos los Clientes', 'robertochoa' ),
        'add_new_item'          => __( 'Agregar Nuevo Cliente', 'robertochoa' ),
        'add_new'               => __( 'Agregar Nuevo', 'robertochoa' ),
        'new_item'              => __( 'Nuevo Cliente', 'robertochoa' ),
        'edit_item'             => __( 'Editar Cliente', 'robertochoa' ),
        'update_item'           => __( 'Actualizar Cliente', 'robertochoa' ),
        'view_item'             => __( 'Ver Cliente', 'robertochoa' ),
        'view_items'            => __( 'Ver Clientes', 'robertochoa' ),
        'search_items'          => __( 'Buscar Cliente', 'robertochoa' ),
        'not_found'             => __( 'No hay resultados', 'robertochoa' ),
        'not_found_in_trash'    => __( 'No hay resultados en Papelera', 'robertochoa' ),
        'featured_image'        => __( 'Imagen del Cliente', 'robertochoa' ),
        'set_featured_image'    => __( 'Colocar Imagen del Cliente', 'robertochoa' ),
        'remove_featured_image' => __( 'Remover Imagen del Cliente', 'robertochoa' ),
        'use_featured_image'    => __( 'Usar como Imagen del Cliente', 'robertochoa' ),
        'insert_into_item'      => __( 'Insertar en Cliente', 'robertochoa' ),
        'uploaded_to_this_item' => __( 'Cargado a este Cliente', 'robertochoa' ),
        'items_list'            => __( 'Listado de Clientes', 'robertochoa' ),
        'items_list_navigation' => __( 'Navegación del Listado de Cliente', 'robertochoa' ),
        'filter_items_list'     => __( 'Filtro del Listado de Clientes', 'robertochoa' ),
    );
    $args = array(
        'label'                 => __( 'Cliente', 'robertochoa' ),
        'description'           => __( 'Portafolio de Clientes', 'robertochoa' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'taxonomies'            => array( 'tipos-de-clientes' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 15,
        'menu_icon'             => 'dashicons-businessperson',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
        'show_in_rest'          => true,
    );
    register_post_type( 'clientes', $args );


    $labels2 = array(
        'name'                  => _x( 'Servicios', 'Post Type General Name', 'robertochoa' ),
        'singular_name'         => _x( 'Servicio', 'Post Type Singular Name', 'robertochoa' ),
        'menu_name'             => __( 'Servicios', 'robertochoa' ),
        'name_admin_bar'        => __( 'Servicios', 'robertochoa' ),
        'archives'              => __( 'Archivo de Servicios', 'robertochoa' ),
        'attributes'            => __( 'Atributos de Servicios', 'robertochoa' ),
        'parent_item_colon'     => __( 'Servicio Padre:', 'robertochoa' ),
        'all_items'             => __( 'Todos los Servicios', 'robertochoa' ),
        'add_new_item'          => __( 'Agregar Nuevo Servicio', 'robertochoa' ),
        'add_new'               => __( 'Agregar Nuevo', 'robertochoa' ),
        'new_item'              => __( 'Nuevo Servicio', 'robertochoa' ),
        'edit_item'             => __( 'Editar Servicio', 'robertochoa' ),
        'update_item'           => __( 'Actualizar Servicio', 'robertochoa' ),
        'view_item'             => __( 'Ver Servicio', 'robertochoa' ),
        'view_items'            => __( 'Ver Servicios', 'robertochoa' ),
        'search_items'          => __( 'Buscar Servicio', 'robertochoa' ),
        'not_found'             => __( 'No hay resultados', 'robertochoa' ),
        'not_found_in_trash'    => __( 'No hay resultados en la Papelera', 'robertochoa' ),
        'featured_image'        => __( 'Ícono del Servicio', 'robertochoa' ),
        'set_featured_image'    => __( 'Colocar Ícono del Servicio', 'robertochoa' ),
        'remove_featured_image' => __( 'Remover Ícono del Servicio', 'robertochoa' ),
        'use_featured_image'    => __( 'Usar como Ícono del Servicio', 'robertochoa' ),
        'insert_into_item'      => __( 'Insertar en Servicio', 'robertochoa' ),
        'uploaded_to_this_item' => __( 'Cargado a este Servicio', 'robertochoa' ),
        'items_list'            => __( 'Listado de Servicios', 'robertochoa' ),
        'items_list_navigation' => __( 'Navegación del Listado de Servicios', 'robertochoa' ),
        'filter_items_list'     => __( 'Filtro del Listado de Servicios', 'robertochoa' ),
    );
    $args2 = array(
        'label'                 => __( 'Servicio', 'robertochoa' ),
        'description'           => __( 'Servicios ofrecidos', 'robertochoa' ),
        'labels'                => $labels2,
        'supports'              => array( 'title', 'editor', 'excerpt', 'thumbnail' ),
        'taxonomies'            => array( 'tipo-de-servicios' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 15,
        'menu_icon'             => 'dashicons-sos',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'show_in_rest'          => true,
    );
    register_post_type( 'servicios', $args2 );
}

add_action( 'init', 'robertochoa_custom_post_type', 0 );
